version: "3"

services:
  app:
    build: .
    restart: unless-stopped
    # ports:
    #   - "3000:3000"
    environment:
      VIRTUAL_HOST: planning.lars-rickert.de
      LETSENCRYPT_HOST: planning.lars-rickert.de

networks:
  default:
    name: nginx-proxy
    external: true
